version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-nodejs-lts
      - test-nodejs-latest
jobs:
  test-nodejs-lts: &test-template
    working_directory: ~/to-cubic
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: npm-update
          command: 'npm install -g npm@latest'
      - restore_cache:
          key: npm-update-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - restore_cache:
          key: npm-install-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run lint && npm run test:report
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'test/results.xml'
          when: always
      - store_artifacts:
          path: test/results.xml
      - store_test_results:
          path: test/results.xml
  test-nodejs-latest:
    <<: *test-template
    docker:
      - image: node:latest
